### ISSUE TITLE
Getting negative loss values

### ISSUE THREAD

**Issue by muhammadahsan** [IParraMartin/Sparse-Autoencoder#1]
Hi, 
Thanks for the work you have done!
I'm asking about the negative loss values that I'm getting during training as shown below:
Is that fine with the training?
I'm training this SAE with my own image data with 4 classes. 
Epoch [1/20], Loss: 0.1413
Epoch [2/20], Loss: -0.4547
Epoch [3/20], Loss: -0.6560
Epoch [4/20], Loss: -0.7508
Epoch [5/20], Loss: -0.8247
Epoch [6/20], Loss: -0.8937
Epoch [7/20], Loss: -0.9350
Epoch [8/20], Loss: -0.9720
Epoch [9/20], Loss: -1.0035
Epoch [10/20], Loss: -1.0318
Epoch [11/20], Loss: -1.0579
Epoch [12/20], Loss: -1.0810
Epoch [13/20], Loss: -1.1018
Epoch [14/20], Loss: -1.1212
Epoch [15/20], Loss: -1.1385
Epoch [16/20], Loss: -1.1550
Epoch [17/20], Loss: -1.1709
Epoch [18/20], Loss: -1.1859
Epoch [19/20], Loss: -1.1998
Epoch [20/20], Loss: -1.2130

**Comment by IParraMartin** [comment]
@muhammadahsan Thank you for the comment! 
I will review the code today. I think that the problem may be caused by the sparsity penalty function. I remember coming across the same issue back when I created the repo.

I will modify this and let you know!

**Comment by IParraMartin** [comment]
Please try now! It works for me on MNIST

**Comment by muhammadahsan** [comment]
It's working perfectly.
Thanks!
